version: '3'
services:
  web:
    image: 026885260290.dkr.ecr.eu-west-1.amazonaws.com/sphere-api:v0.0.1
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: api
        awslogs-region: eu-west-1
        awslogs-stream-prefix: api